name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Go to Dart directory
      run: cd dart
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
