name: Dart

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: cedx/setup-dart@v1
    - name: Run tests
      run: |
        cd dart
        pub get
        pub run test --coverage=coverage --file-reporter=compact:tests.output
        pub run test_coverage
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        echo `git add -A && git commit -m "Change Dart Coverage Badge"`
        git pull --rebase
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v1
    - name: Run sonarqube
      run: sonar-scanner
          -Dsonar.projectBaseDir=dart
          -Dsonar.login=306e2f3ca2900db52fbd87dbb771ad1ef559450b
          -Dsonar.host.url=https://sonar.techmeup.io
          -Dsonar.projectKey=dart_katas
          -Dsonar.sources=lib
          -Dsonar.tests=test
          -Dsonar.projectVersion=1.0
          -Dsonar.sourceEncoding=UTF-8
          -Dsonar.testExecutionReportPaths=dart/coverage
