name: TypeScript

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        cd typescript
        npm install
        npm run test
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        echo `git add -A && git commit -m "Change TypeScript Coverage Badge"`
        git pull --rebase
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v1
    - name: Run sonarqube
      run: sonar-scanner
          -Dsonar.login=543e7e2282f3234946db8c410b6a1870e37a817c
          -Dsonar.host.url=https://sonar.techmeup.io
          -Dsonar.projectKey=typescript_katas
          -Dsonar.sources=typescript/src
          -Dsonar.projectVersion=1.0
          -Dsonar.sourceEncoding=UTF-8
          -Dsonar.php.coverage.reportPaths=typescript/coverage/clover.xml
