name: PHP

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run test suite
      run: |
        cd php
        composer install
        vendor/bin/phpunit tests --coverage-clover coverage.xml
        vendor/bin/php-coverage-badger coverage.xml coverage.svg
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        echo `git add -A && git commit -m "Change PHP Coverage Badge"`
        git pull --rebase
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
