name: PHP

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run test suite
      run: |
        cd php
        composer install
        vendor/bin/phpunit tests --coverage-clover coverage.xml
        vendor/bin/php-coverage-badger coverage.xml coverage.svg
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        echo `git add -A && git commit -m "Change PHP Coverage Badge"`
        git pull --rebase
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v1
    - name: Run sonarqube
      run: sonar-scanner
          -Dsonar.login=0af39eab949ef590ea4ba17345c9c0cb8c60f6af
          -Dsonar.host.url=https://sonar.techmeup.io
          -Dsonar.projectKey=php_katas
          -Dsonar.sources=php/src
          -Dsonar.projectVersion=1.0
          -Dsonar.sourceEncoding=UTF-8
          -Dsonar.php.coverage.reportPaths=php/coverage.xml
