name: Python

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --unshallow
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        cd python
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        cd python
        flake8 . -v
    - name: Launch tests
      run: |
        cd python
        coverage run -m unittest discover -v
        coverage report -m
        coverage xml
        rm coverage.svg
        coverage-badge -o coverage.svg
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        echo `git add -A && git commit -m "Change Python Coverage Badge"`
        git pull --rebase
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v1
    - name: Run sonarqube
      run: |
        sonar-scanner
        -Dsonar.login=3f5f2ea453490899d2a512389f40329906a908b4
        -Dsonar.host.url=https://sonar.techmeup.io
        -Dsonar.projectKey=python_katas
        -Dsonar.sources=python/src
        -Dsonar.projectVersion=1.0
        -Dsonar.sourceEncoding=UTF-8
        -Dsonar.python.coverage.reportPaths=python/coverage.xml
